spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#整合mybatis
mybatis:
  type-aliases-package: com.baidu.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
